export const ADD_HELP_TEXT = [
  "📖 **How to use /add**",
  "",
  "**Usage:** `/add <symbol> [type]`",
  "",
  "Track a stock, ETF, or cryptocurrency in your watchlist.",
  "",
  "**Parameters:**",
  "• `symbol` — The ticker symbol (e.g. AAPL, SPY, BTC)",
  "• `type` — Optional: `stock` (default), `etf`, or `crypto`",
  "",
  "**Examples:**",
  "`/add AAPL` — add a stock (default type)",
  "`/add AAPL stock` — explicitly add as stock",
  "`/add SPY etf` — add an ETF",
  "`/add BTC crypto` — add a cryptocurrency",
  "`/add ETH crypto` — add Ethereum",
  "",
  "**Notes:**",
  "• If type is omitted, it defaults to `stock`",
  "• Crypto symbols are auto-normalized (BTC → BTC/USD)",
  "• Free tier is limited to 5 tickers — upgrade to Pro for unlimited",
  "• New tickers may take 15 min to 1 hour for data to populate",
].join("\n");
