export const COMMAND_MENU = [
  "**Commands:**",
  "/start - Register or pair via deep link",
  "/pair <code> - Link your web account",
  "/login - Start a new session",
  "/logout - End your current session",
  "/refresh - Clear previous chat session and start fresh",
  "/status - Check your session status",
  "/add <symbol> [type] - Track a ticker (stock, etf, crypto)",
  "/remove <symbol> - Stop tracking a ticker",
  "/wishlist or /watchlist - View your tracked tickers with price targets",
  "/subscribe - Upgrade to Pro or start a free trial",
  "/alert - Toggle Smart Digest on/off",
  "/help - Show available commands",
  "/addhelp - How to use /add",
  "/removehelp - How to use /remove",
].join("\n");
