// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTracker.Data;

#nullable disable

namespace StockTracker.Data.Migrations.Migrations
{
    [DbContext(typeof(StockTrackerDbContext))]
    [Migration("20251225161041_AddAiHubTables")]
    partial class AddAiHubTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTracker.Data.Entities.AiHubLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CallerService")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("caller_service");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("GoogleProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_project_id");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("MessagePreview")
                        .HasColumnType("text")
                        .HasColumnName("message_preview");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("model_id");

                    b.Property<string>("RateLimitType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rate_limit_type");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponsePreview")
                        .HasColumnType("text")
                        .HasColumnName("response_preview");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TokensInput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_input");

                    b.Property<int?>("TokensOutput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_output");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("GoogleProjectId");

                    b.HasIndex("ModelId");

                    b.HasIndex("Status");

                    b.ToTable("ai_hub_logs", null, t =>
                        {
                            t.HasCheckConstraint("ai_hub_logs_status_check", "status IN ('success', 'rate_limited', 'server_error', 'unavailable', 'client_error', 'timeout')");
                        });
                });

            modelBuilder.Entity("StockTracker.Data.Entities.AiHubRateTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DailyRequests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("daily_requests");

                    b.Property<string>("GoogleProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_project_id");

                    b.Property<DateTime>("MinuteWindow")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("minute_window");

                    b.Property<string>("ModelFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_family");

                    b.Property<DateOnly>("PacificDate")
                        .HasColumnType("date")
                        .HasColumnName("pacific_date");

                    b.Property<int>("RequestsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("requests_count");

                    b.Property<int>("TokensCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokens_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GoogleProjectId", "ModelFamily", "MinuteWindow")
                        .IsUnique()
                        .IsDescending(false, false, true);

                    b.ToTable("ai_hub_rate_tracking", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CryptoTickerId")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_ticker_id");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("low_price");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(24,2)")
                        .HasColumnName("market_cap");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("open_price");

                    b.Property<DateTime>("PriceTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_time");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(24,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PriceTime");

                    b.HasIndex("CryptoTickerId", "PriceTime");

                    b.HasIndex("CryptoTickerId", "DataSourceId", "PriceTime")
                        .IsUnique();

                    b.ToTable("crypto_prices", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoTicker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<int>("UniverseId")
                        .HasColumnType("integer")
                        .HasColumnName("universe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("is_active = true");

                    b.HasIndex("Slug");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UniverseId");

                    b.ToTable("crypto_tickers", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<string>("ApiSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("api_secret_encrypted");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("api_key")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_headers");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("prod")
                        .HasColumnName("environment");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OAuthClientIdEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("oauth_client_id_encrypted");

                    b.Property<string>("OAuthClientSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("oauth_client_secret_encrypted");

                    b.Property<string>("OAuthTokenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("oauth_token_url");

                    b.Property<int?>("RateLimitPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_per_day");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_per_minute");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("retry_count");

                    b.Property<bool>("SupportsCrypto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_crypto");

                    b.Property<bool>("SupportsStocks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_stocks");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.FetchSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FetchConfig")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("fetch_config");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LastRunMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_run_message");

                    b.Property<string>("LastRunStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_run_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("ScheduleTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(22, 0, 0))
                        .HasColumnName("schedule_time_utc");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_fetch_schedules_data_source_id");

                    b.ToTable("fetch_schedules", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("low_price");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("open_price");

                    b.Property<DateTime>("PriceTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_time");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_ticker_id");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PriceTime");

                    b.HasIndex("StockTickerId", "PriceTime");

                    b.HasIndex("StockTickerId", "DataSourceId", "PriceTime")
                        .IsUnique();

                    b.ToTable("stock_prices", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockTicker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<int>("UniverseId")
                        .HasColumnType("integer")
                        .HasColumnName("universe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("is_active = true");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UniverseId");

                    b.ToTable("stock_tickers", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.Universe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("universe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 25, 16, 10, 41, 573, DateTimeKind.Utc).AddTicks(9980),
                            IsActive = true,
                            Name = "stock",
                            UpdatedAt = new DateTime(2025, 12, 25, 16, 10, 41, 573, DateTimeKind.Utc).AddTicks(9982)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 25, 16, 10, 41, 573, DateTimeKind.Utc).AddTicks(9983),
                            IsActive = true,
                            Name = "etf",
                            UpdatedAt = new DateTime(2025, 12, 25, 16, 10, 41, 573, DateTimeKind.Utc).AddTicks(9983)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 25, 16, 10, 41, 573, DateTimeKind.Utc).AddTicks(9984),
                            IsActive = true,
                            Name = "crypto",
                            UpdatedAt = new DateTime(2025, 12, 25, 16, 10, 41, 573, DateTimeKind.Utc).AddTicks(9985)
                        });
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoPrice", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.CryptoTicker", "CryptoTicker")
                        .WithMany("Prices")
                        .HasForeignKey("CryptoTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockTracker.Data.Entities.DataSource", "DataSource")
                        .WithMany("CryptoPrices")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoTicker");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoTicker", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.Universe", "Universe")
                        .WithMany("CryptoTickers")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.FetchSchedule", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_fetch_schedules_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockPrice", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.DataSource", "DataSource")
                        .WithMany("StockPrices")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockTracker.Data.Entities.StockTicker", "StockTicker")
                        .WithMany("Prices")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockTicker", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.Universe", "Universe")
                        .WithMany("StockTickers")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoTicker", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.DataSource", b =>
                {
                    b.Navigation("CryptoPrices");

                    b.Navigation("StockPrices");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockTicker", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.Universe", b =>
                {
                    b.Navigation("CryptoTickers");

                    b.Navigation("StockTickers");
                });
#pragma warning restore 612, 618
        }
    }
}
