// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTracker.Data;

#nullable disable

namespace StockTracker.Data.Migrations.Migrations
{
    [DbContext(typeof(StockTrackerDbContext))]
    [Migration("20260126073511_RenameLookupTables")]
    partial class RenameLookupTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTracker.Data.Entities.AiHubLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CallerService")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("caller_service");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("GoogleProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_project_id");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("MessagePreview")
                        .HasColumnType("text")
                        .HasColumnName("message_preview");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("model_id");

                    b.Property<string>("RateLimitType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rate_limit_type");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponsePreview")
                        .HasColumnType("text")
                        .HasColumnName("response_preview");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TokensInput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_input");

                    b.Property<int?>("TokensOutput")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_output");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("GoogleProjectId");

                    b.HasIndex("ModelId");

                    b.HasIndex("Status");

                    b.ToTable("ai_hub_logs", null, t =>
                        {
                            t.HasCheckConstraint("ai_hub_logs_status_check", "status IN ('success', 'rate_limited', 'server_error', 'unavailable', 'client_error', 'timeout')");
                        });
                });

            modelBuilder.Entity("StockTracker.Data.Entities.AiHubRateTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DailyRequests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("daily_requests");

                    b.Property<string>("GoogleProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_project_id");

                    b.Property<DateTime>("MinuteWindow")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("minute_window");

                    b.Property<string>("ModelFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_family");

                    b.Property<DateOnly>("PacificDate")
                        .HasColumnType("date")
                        .HasColumnName("pacific_date");

                    b.Property<int>("RequestsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("requests_count");

                    b.Property<int>("TokensCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokens_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GoogleProjectId", "ModelFamily", "MinuteWindow")
                        .IsUnique()
                        .IsDescending(false, false, true);

                    b.ToTable("ai_hub_rate_tracking", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.AnalysisStockCandlestickPattern", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AnalysisDate")
                        .HasColumnType("date")
                        .HasColumnName("analysis_date");

                    b.Property<string>("AnalysisVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("1.0.0")
                        .HasColumnName("analysis_version");

                    b.Property<decimal?>("BodySize")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("body_size");

                    b.Property<int>("CandlesAggregated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("candles_aggregated");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("DailyClose")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("daily_close");

                    b.Property<decimal?>("DailyHigh")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("daily_high");

                    b.Property<decimal?>("DailyLow")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("daily_low");

                    b.Property<decimal?>("DailyOpen")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("daily_open");

                    b.Property<long?>("DailyVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("daily_volume");

                    b.Property<string>("DetectedPatterns")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("detected_patterns");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bullish");

                    b.Property<decimal?>("LowerWick")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("lower_wick");

                    b.Property<decimal?>("RangeSize")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("range_size");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_ticker_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("UpperWick")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("upper_wick");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDate");

                    b.HasIndex("StockTickerId", "AnalysisDate")
                        .IsUnique();

                    b.ToTable("analysis_stock_candlestick_pattern", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CryptoTickerId")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_ticker_id");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("low_price");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(24,2)")
                        .HasColumnName("market_cap");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(24,12)")
                        .HasColumnName("open_price");

                    b.Property<DateTime>("PriceTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_time");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(24,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PriceTime");

                    b.HasIndex("CryptoTickerId", "PriceTime");

                    b.HasIndex("CryptoTickerId", "DataSourceId", "PriceTime")
                        .IsUnique();

                    b.ToTable("crypto_prices", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoTicker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<int>("UniverseId")
                        .HasColumnType("integer")
                        .HasColumnName("universe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("is_active = true");

                    b.HasIndex("Slug");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UniverseId");

                    b.ToTable("crypto_tickers", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<string>("ApiSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("api_secret_encrypted");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("api_key")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_headers");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("prod")
                        .HasColumnName("environment");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OAuthClientIdEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("oauth_client_id_encrypted");

                    b.Property<string>("OAuthClientSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("oauth_client_secret_encrypted");

                    b.Property<string>("OAuthTokenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("oauth_token_url");

                    b.Property<int?>("RateLimitPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_per_day");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_per_minute");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("retry_count");

                    b.Property<bool>("SupportsCrypto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_crypto");

                    b.Property<bool>("SupportsStocks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_stocks");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("lookup_data_sources", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("low_price");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("open_price");

                    b.Property<DateTime>("PriceTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_time");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_ticker_id");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PriceTime");

                    b.HasIndex("StockTickerId", "PriceTime");

                    b.HasIndex("StockTickerId", "DataSourceId", "PriceTime")
                        .IsUnique();

                    b.ToTable("stock_prices", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockTicker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<int>("UniverseId")
                        .HasColumnType("integer")
                        .HasColumnName("universe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("is_active = true");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UniverseId");

                    b.ToTable("stock_tickers", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("CancelAtPeriodEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_price_id");

                    b.Property<string>("StripeProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_product_id");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTime?>("TrialEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_end");

                    b.Property<DateTime?>("TrialStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_start");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.SubscriptionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("previous_status");

                    b.Property<string>("StripeEventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_event_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId");

                    b.HasIndex("UserId");

                    b.ToTable("subscription_history", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.TelegramRateLimit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_count");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTime>("WindowStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId", "ActionType")
                        .IsUnique();

                    b.ToTable("telegram_rate_limits", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.TelegramSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CursorChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("cursor_chat_id");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("device_info")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastActiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SessionToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_token")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CursorChatId")
                        .HasFilter("cursor_chat_id IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("telegram_sessions", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.TelegramUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("telegram_username");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("telegram_users", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.Universe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("lookup_universe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 35, 11, 12, DateTimeKind.Utc).AddTicks(6799),
                            IsActive = true,
                            Name = "stock",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 35, 11, 12, DateTimeKind.Utc).AddTicks(6799)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 35, 11, 12, DateTimeKind.Utc).AddTicks(6801),
                            IsActive = true,
                            Name = "etf",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 35, 11, 12, DateTimeKind.Utc).AddTicks(6801)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 26, 7, 35, 11, 12, DateTimeKind.Utc).AddTicks(6803),
                            IsActive = true,
                            Name = "crypto",
                            UpdatedAt = new DateTime(2026, 1, 26, 7, 35, 11, 12, DateTimeKind.Utc).AddTicks(6803)
                        });
                });

            modelBuilder.Entity("StockTracker.Data.Entities.WorkerFetchSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FetchConfig")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("fetch_config");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LastRunMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_run_message");

                    b.Property<string>("LastRunStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_run_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("ScheduleTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(22, 0, 0))
                        .HasColumnName("schedule_time_utc");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_worker_fetch_schedules_data_source_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_worker_fetch_schedules_worker_id");

                    b.ToTable("worker_fetch_schedules", (string)null);
                });

            modelBuilder.Entity("StockTracker.Data.Entities.AnalysisStockCandlestickPattern", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.StockTicker", "StockTicker")
                        .WithMany("CandlestickPatterns")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoPrice", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.CryptoTicker", "CryptoTicker")
                        .WithMany("Prices")
                        .HasForeignKey("CryptoTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockTracker.Data.Entities.DataSource", "DataSource")
                        .WithMany("CryptoPrices")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoTicker");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoTicker", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.Universe", "Universe")
                        .WithMany("CryptoTickers")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockPrice", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.DataSource", "DataSource")
                        .WithMany("StockPrices")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockTracker.Data.Entities.StockTicker", "StockTicker")
                        .WithMany("Prices")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockTicker", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.Universe", "Universe")
                        .WithMany("StockTickers")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.TelegramSession", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.TelegramUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.WorkerFetchSchedule", b =>
                {
                    b.HasOne("StockTracker.Data.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_worker_fetch_schedules_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.CryptoTicker", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.DataSource", b =>
                {
                    b.Navigation("CryptoPrices");

                    b.Navigation("StockPrices");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.StockTicker", b =>
                {
                    b.Navigation("CandlestickPatterns");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.TelegramUser", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("StockTracker.Data.Entities.Universe", b =>
                {
                    b.Navigation("CryptoTickers");

                    b.Navigation("StockTickers");
                });
#pragma warning restore 612, 618
        }
    }
}
